tasks:
  - name: Setup MySQL
    command: sudo service mysql start
    background: true
    init: true

  - name: Install MySQL Client
    command: sudo apt-get install -y mysql-client

  - name: Install Python Dependencies
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip
      pip install -r requirements.txt
      
  - name: Install Dependencies
    command: |
      npm install
      # Outros comandos de instalação, se necessário

  - name: Start Web Application
    command: npm start
    openMode: tab

ports:
  - 8080
  - 3306
