[default]
SQLALCHEMY_DATABASE_URI = 'mysql+pymysql://gustavo:123456@localhost:3306/HPC'
SECRET_KEY = "secreto"
SQLALCHEMY_TRACK_MODIFICATIONS = false
UPLOAD_EXTENSIONS = ['.jpg','.png','.gif','.jpeg','.pdf']
UPLOAD_PATH = 'uploads'

